[package]
name = "repro-napi-20230614"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "addon"

[dependencies]
napi = { version = "2.13.2", features = ["napi8", "tokio_rt", "serde-json"] }
napi-derive = "2.13.0"

[build-dependencies]
napi-build = "2.0.1"
